pluginManagement {
    plugins {
        id 'io.ballerina.plugin' version "${ballerinaGradlePluginVersion}"
    }

    repositories {
        gradlePluginPortal()
        maven {
            url = 'https://maven.pkg.github.com/ballerina-platform/*'
            credentials {
                username System.getenv("packageUser")
                password System.getenv("packagePAT")
            }
        }
    }
}

rootProject.name = 'bal-discover-tool'

include ':native'
include ':bal-tool'

project(':native').projectDir = file('native')
project(':bal-tool').projectDir = file('bal-tool')
